#name: GitHub Actions Demo
#run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
#on: [push]
#jobs:
#  Explore-GitHub-Actions:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
#        uses: actions/checkout@v4
#      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#      - name: List files in the repository
#        run: |
#          ls ${{ github.workspace }}
#      - run: echo "ğŸ This job's status is ${{ job.status }}."

name: Check Snapshot in TOML
on:
  [push]
jobs:
  check_snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "snapshot" in TOML
        run: |
          if grep -q "SNAPSHOT" $(find . -type f -name "*.toml"); then
            echo "Snapshot found in TOML file(s)."
            exit 1
          else
            echo "No snapshot found in TOML file(s)."
          fi
      - run: pwd
      - run: find . -type f -name "*.toml"
      - run: ls $(pwd)
      - name: List files in directory
        run: ls -R
